# Generated by Django 5.0.1 on 2024-01-06 14:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=50, verbose_name='Ady we famaliýasy')),
                ('avatar', models.ImageField(upload_to='doctors_images', verbose_name='Lukmanyň şahsy suraty')),
                ('about', models.TextField(max_length=500, verbose_name='Lukman barada')),
            ],
            options={
                'verbose_name_plural': 'Lukmanlar',
            },
        ),
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender_type', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Smen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_part', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Baby',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(max_length=25, verbose_name='Maşgala familiýasy')),
                ('avatar', models.ImageField(upload_to='babies_images', verbose_name='Suraty')),
                ('born_time', models.DateTimeField(verbose_name='Dogulan wagty')),
                ('weight', models.IntegerField(verbose_name='Agramy')),
                ('is_alive', models.BooleanField(default=True, verbose_name='Ýaşaýşa dowam')),
                ('babydoctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='baby_born_app.doctor', verbose_name='Lukmany')),
                ('gender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='baby_born_app.gender', verbose_name='Jynsy')),
            ],
        ),
        migrations.AddField(
            model_name='doctor',
            name='work_time',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='baby_born_app.smen'),
        ),
    ]
