# Generated by Django 5.0.1 on 2024-01-06 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baby_born_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carousel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='Carousel_images', verbose_name='Karusel suraty')),
                ('title', models.CharField(max_length=50, verbose_name='Karusel tema ady')),
                ('about', models.CharField(max_length=100, verbose_name='Karusel beýany')),
            ],
        ),
    ]
